// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yuebczafcrrmtvfuzkvf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1ZWJjemFmY3JybXR2ZnV6a3ZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3Mjc0NDksImV4cCI6MjA3NDMwMzQ0OX0.C0p2ECqqERPoFDU2qKWErbLGchGVSm-pTIYdeDosx9I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});